---
name: Nuki Bridge
description: Virtual Nuki Bridge to use instead of the physical device
version: 0.0.23-alpha.7
slug: nuki_bridge
url: https://github.com/regevbr/RaspiNukiBridge
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Bridge api port
host_dbus: true
image: ghcr.io/regevbr/nuki_bridge/{arch}
options:
  adapter: hci0
  command_timeout: 30
  connection_timeout: 10
  retry: 5
schema:
  adapter: str
  command_timeout: float
  connection_timeout: float
  retry: int
